// Code generated by scripts/generate-native-types.mjs from src/NativeLoginResult.d.ts.
// DO NOT EDIT — re-run `npm run generate-native-types` after changing the d.ts.

import ExpoModulesCore

enum NativeLoginResult {
  struct Success: Record {
    @Field var kind: String = "Success"
    @Field var idToken: String = ""
    @Field var traceId: String = ""

    init() {}

    init(idToken: String, traceId: String) {
      self.idToken = idToken
      self.traceId = traceId
    }
  }

  struct UserCancelled: Record {
    @Field var kind: String = "UserCancelled"
    @Field var traceId: String? = nil

    init() {}

    init(traceId: String? = nil) {
      self.traceId = traceId
    }
  }

  struct NoSuitableBrowser: Record {
    @Field var kind: String = "NoSuitableBrowser"
    @Field var traceId: String? = nil

    init() {}

    init(traceId: String? = nil) {
      self.traceId = traceId
    }
  }

  struct OAuthError: Record {
    @Field var kind: String = "OAuthError"
    @Field var error: String = ""
    @Field var errorDescription: String? = nil
    @Field var traceId: String? = nil

    init() {}

    init(error: String, errorDescription: String? = nil, traceId: String? = nil) {
      self.error = error
      self.errorDescription = errorDescription
      self.traceId = traceId
    }
  }

  struct InternalError: Record {
    @Field var kind: String = "InternalError"
    @Field var message: String = ""
    @Field var traceId: String? = nil

    init() {}

    init(message: String, traceId: String? = nil) {
      self.message = message
      self.traceId = traceId
    }
  }

  struct ModuleNotConfigured: Record {
    @Field var kind: String = "ModuleNotConfigured"
    @Field var message: String = ""

    init() {}

    init(message: String) {
      self.message = message
    }
  }

  struct UnknownPrompt: Record {
    @Field var kind: String = "UnknownPrompt"
    @Field var value: String = ""

    init() {}

    init(value: String) {
      self.value = value
    }
  }
}
