// Code generated by scripts/generate-native-types.mjs from src/NativeLoginResult.d.ts.
// DO NOT EDIT — re-run `npm run generate-native-types` after changing the d.ts.

package expo.modules.criiptoverify

import expo.modules.kotlin.records.Field
import expo.modules.kotlin.records.Record

sealed interface NativeLoginResult : Record {
  val kind: String

  class Success : NativeLoginResult {
    @Field override var kind: String = "Success"

    @Field var idToken: String = ""
  }

  class UserCancelled : NativeLoginResult {
    @Field override var kind: String = "UserCancelled"
  }

  class NoSuitableBrowser : NativeLoginResult {
    @Field override var kind: String = "NoSuitableBrowser"
  }

  class OAuthError : NativeLoginResult {
    @Field override var kind: String = "OAuthError"

    @Field var error: String = ""

    @Field var errorDescription: String? = null
  }

  class InternalError : NativeLoginResult {
    @Field override var kind: String = "InternalError"

    @Field var message: String = ""
  }

  class ModuleNotConfigured : NativeLoginResult {
    @Field override var kind: String = "ModuleNotConfigured"

    @Field var message: String = ""
  }

  class UnknownPrompt : NativeLoginResult {
    @Field override var kind: String = "UnknownPrompt"

    @Field var value: String = ""
  }
}
